extends Node
class_name BuildingCatalog

const ORDER := [
	"grunt_tower",
	"stone_tower",
	"archer_tower",
	"woodcutter",
	"stonecutter",
	"iron_miner",
	"archery_range",
	"barracks",
	"house",
	"farm",
	"wood_storage",
	"food_storage",
	"stone_storage",
	"iron_storage",
]
const CATEGORY_ORDER := ["Towers", "Production", "Military", "Housing", "Storage"]

func get_order() -> Array[String]:
	var order: Array[String] = []
	for building_id in ORDER:
		order.append(building_id)
	return order

func get_categories() -> Array[String]:
	var categories: Array[String] = []
	for category in CATEGORY_ORDER:
		categories.append(category)
	return categories

func build_defs(main: Node) -> Dictionary:
	return {
		"grunt_tower": {
			"label": "Grunt Tower",
			"category": "Towers",
			"spawn_type": "script",
			"path": "res://scripts/GruntTower.gd",
			"size": 1,
			"placement": "grid",
			"costs": {"wood": main.tower_cost},
			"build_time": main.build_time_tower,
			"requirements": [{"type": "base_level", "value": 1}],
			"uses_occupied": true,
		},
		"stone_tower": {
			"label": "Stone Tower",
			"category": "Towers",
			"spawn_type": "script",
			"path": "res://scripts/StoneTower.gd",
			"size": 1,
			"placement": "grid",
			"costs": {"stone": 10},
			"build_time": main.build_time_tower,
			"requirements": [
				{"type": "base_level", "value": 1},
				{"type": "archery_level", "value": 1},
			],
			"uses_occupied": true,
		},
		"archer_tower": {
			"label": "Archer Tower",
			"category": "Towers",
			"spawn_type": "script",
			"path": "res://scripts/ArcherTower.gd",
			"size": 1,
			"placement": "grid",
			"costs": {"wood": 10, "stone": 10},
			"build_time": main.build_time_tower,
			"requirements": [
				{"type": "base_level", "value": 1},
				{"type": "archery_level", "value": 2},
			],
			"uses_occupied": true,
		},
		"woodcutter": {
			"label": "Woodcutter",
			"category": "Production",
			"spawn_type": "scene",
			"path": "res://scenes/Woodcutter.tscn",
			"size": 2,
			"placement": "tree",
			"costs": {"wood": main.woodcutter_cost},
			"build_time": main.build_time_woodcutter,
			"requirements": [{"type": "base_level", "value": 1}],
			"resource_kind": "wood",
		},
		"stonecutter": {
			"label": "Stonecutter",
			"category": "Production",
			"spawn_type": "scene",
			"path": "res://scenes/Stonecutter.tscn",
			"size": 2,
			"placement": "stone",
			"costs": {"wood": main.stonecutter_cost},
			"build_time": main.build_time_stonecutter,
			"requirements": [{"type": "base_level", "value": 2}],
			"resource_kind": "stone",
		},
		"iron_miner": {
			"label": "Iron Miner",
			"category": "Production",
			"spawn_type": "scene",
			"path": "res://scenes/IronMiner.tscn",
			"size": 2,
			"placement": "iron",
			"costs": {"wood": main.iron_miner_cost},
			"build_time": main.build_time_iron_miner,
			"requirements": [{"type": "base_level", "value": 3}],
			"resource_kind": "iron",
		},
		"archery_range": {
			"label": "Archery Range",
			"category": "Military",
			"spawn_type": "scene",
			"path": "res://scenes/ArcheryRange.tscn",
			"size": 3,
			"placement": "grid",
			"costs": {"wood": main.archery_range_cost},
			"build_time": main.build_time_archery_range,
			"requirements": [{"type": "base_level", "value": 2}],
			"effect": "archery_range",
		},
		"barracks": {
			"label": "Barracks",
			"category": "Military",
			"spawn_type": "scene",
			"path": "res://scenes/Barracks.tscn",
			"size": 3,
			"placement": "grid",
			"costs": {"wood": main.barracks_wood_cost, "stone": main.barracks_stone_cost},
			"build_time": main.build_time_barracks,
			"requirements": [{"type": "base_level", "value": 3}],
			"effect": "barracks",
		},
		"house": {
			"label": "House",
			"category": "Housing",
			"spawn_type": "scene",
			"path": "res://scenes/House.tscn",
			"size": 2,
			"placement": "grid",
			"costs": {"wood": main.house_cost},
			"build_time": main.build_time_house,
			"requirements": [{"type": "base_level", "value": 1}],
			"effect": "house",
		},
		"farm": {
			"label": "Farm",
			"category": "Production",
			"spawn_type": "scene",
			"path": "res://scenes/Farm.tscn",
			"size": 2,
			"placement": "grid",
			"costs": {"wood": main.farm_cost},
			"build_time": main.build_time_farm,
			"requirements": [{"type": "base_level", "value": 1}],
			"effect": "farm",
		},
		"wood_storage": {
			"label": "Wood Storage",
			"category": "Storage",
			"spawn_type": "scene",
			"path": "res://scenes/WoodStorage.tscn",
			"size": 2,
			"placement": "grid",
			"costs": {"wood": main.wood_storage_cost},
			"build_time": main.build_time_wood_storage,
			"requirements": [{"type": "base_level", "value": 1}],
			"effect": "wood_storage",
		},
		"food_storage": {
			"label": "Food Storage",
			"category": "Storage",
			"spawn_type": "scene",
			"path": "res://scenes/FoodStorage.tscn",
			"size": 2,
			"placement": "grid",
			"costs": {"wood": main.food_storage_cost},
			"build_time": main.build_time_food_storage,
			"requirements": [{"type": "base_level", "value": 1}],
			"effect": "food_storage",
		},
		"stone_storage": {
			"label": "Stone Storage",
			"category": "Storage",
			"spawn_type": "scene",
			"path": "res://scenes/StoneStorage.tscn",
			"size": 2,
			"placement": "grid",
			"costs": {"wood": main.stone_storage_cost},
			"build_time": main.build_time_stone_storage,
			"requirements": [{"type": "base_level", "value": 2}],
			"effect": "stone_storage",
		},
		"iron_storage": {
			"label": "Iron Storage",
			"category": "Storage",
			"spawn_type": "scene",
			"path": "res://scenes/IronStorage.tscn",
			"size": 2,
			"placement": "grid",
			"costs": {"wood": main.iron_storage_cost},
			"build_time": main.build_time_iron_storage,
			"requirements": [{"type": "base_level", "value": 3}],
			"effect": "iron_storage",
		},
	}
